apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-monitoring
# resources:
# disable randomized suffix generation
configMapGenerator:
  - name: cluster-monitoring-config
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
