apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    app.kubernetes.io/component: admission
    toolkit.fluxcd.io/tenant: platform-team
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: admission
    toolkit.fluxcd.io/tenant: platform-team
  name: flux-admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: kyverno
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: kyverno
  labels:
    app.kubernetes.io/component: admission
    toolkit.fluxcd.io/tenant: platform-team
